{
	"file":"animated/tux_from_linux.png",
	"type":"animated",
	"anim":{
		"columns":3,
		"lines":9,
		"width":56,
		"height":80,
		"reverse":true,
		"speed":80,
		"anims":[
			{
				"name":"idle",
				"start_col":0,
				"end_col":2,
				"start_line":0,
				"end_line":0
			},
			{
				"name":"walk",
				"start_col":0,
				"end_col":2,
				"start_line":1,
				"end_line":1
			},
			{
				"name":"jump",
				"start_col":0,
				"end_col":1,
				"start_line":2,
				"end_line":2,
				"loop":false
			},
			{
				"name":"land",
				"start_col":2,
				"end_col":2,
				"start_line":2,
				"end_line":2
			},
			{
				"name":"hit",
				"start_col":0,
				"end_col":2,
				"start_line":3,
				"end_line":3
			},
			{
				"name":"punch",
				"start_col":0,
				"end_col":2,
				"start_line":4,
				"end_line":4
			},
			{
				"name":"kick",
				"start_col":0,
				"end_col":2,
				"start_line":5,
				"end_line":5
			},
			{
				"name":"propulsion_punch",
				"start_col":0,
				"end_col":2,
				"start_line":6,
				"end_line":6
			},
			{
				"name":"propulsion_kick",
				"start_col":0,
				"end_col":2,
				"start_line":7,
				"end_line":7
			},
			{
				"name":"die",
				"start_col":0,
				"end_col":2,
				"start_line":8,
				"end_line":8
			},
			{
				"name":"dead",
				"start_col":2,
				"end_col":2,
				"start_line":8,
				"end_line":8
			}
		]
	}
}