{
	"file":"animated/VonFlamby.png",
	"type":"animated",
	"anim":{
		"columns":3,
		"lines":4,
		"width":181,
		"height":230,
		"reverse":true,
		"speed":80,
		"anims":[
			{
				"name":"idle",
				"start_col":0,
				"end_col":2,
				"start_line":0,
				"end_line":0
			},
			{
				"name":"walk",
				"start_col":0,
				"end_col":2,
				"start_line":2,
				"end_line":2
			},
			{
				"name":"hit",
				"start_col":0,
				"end_col":0,
				"start_line":3,
				"end_line":3
			},
			{
				"name":"punch",
				"start_col":0,
				"end_col":2,
				"start_line":1,
				"end_line":1
			},
			{
				"name":"kick",
				"start_col":0,
				"end_col":2,
				"start_line":1,
				"end_line":1
			},
			{
				"name":"die",
				"start_col":0,
				"end_col":2,
				"start_line":3,
				"end_line":3
			},
			{
				"name":"dead",
				"start_col":2,
				"end_col":2,
				"start_line":3,
				"end_line":3
			}
		]
	}
}